import streamlit as st
from pathlib import Path


# ── CSS Loader ────────────────────────────────────────────────────────────────


def load_css():
    """Load external CSS file into Streamlit."""
    css_path = Path(__file__).parent / "static" / "style.css"
    with open(css_path) as f:
        css = f.read()
    st.markdown(f"<style>{css}</style>", unsafe_allow_html=True)


# ── Page Header ───────────────────────────────────────────────────────────────


def render_header():
    """Render main page title and subtitle."""
    st.markdown(
        '<div class="main-title">Multi-Document Research Assistant</div>',
        unsafe_allow_html=True,
    )
    st.markdown(
        '<div class="subtitle">Powered by RAG Fusion · Reciprocal Rank Fusion · Groq LLaMA 3.3-70B</div>',
        unsafe_allow_html=True,
    )


def render_status_banner(docs_loaded: bool, doc_count: int, source_count: int):
    """Render status banner showing whether docs are loaded."""
    if not docs_loaded:
        st.markdown(
            """
        <div class="status-box">
            👈 <strong>Get started:</strong> Enter your Groq API key, upload PDFs or
            paste URLs in the sidebar, then click <em>Process Documents</em>.
        </div>
        """,
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            f"""
        <div class="status-box">
            ✅ <strong>{doc_count} chunks</strong> indexed from
            <strong>{source_count} source(s)</strong> — Ask anything about your documents.
        </div>
        """,
            unsafe_allow_html=True,
        )


# ── Sidebar ───────────────────────────────────────────────────────────────────


def render_sidebar_header():
    """Render sidebar branding."""
    st.markdown(
        '<div class="main-title" style="font-size:1.5rem">🔬 Research<br/>Assistant</div>',
        unsafe_allow_html=True,
    )
    st.markdown(
        '<div class="subtitle" style="font-size:0.8rem">RAG Fusion + RRF Reranking</div>',
        unsafe_allow_html=True,
    )


def render_sidebar_stats(doc_count: int, source_names: list):
    """Render document index statistics in sidebar."""
    st.markdown(
        '<div class="sidebar-header">📊 Index Stats</div>', unsafe_allow_html=True
    )

    col1, col2 = st.columns(2)
    with col1:
        st.markdown(
            f'<div class="doc-count">{doc_count}</div>'
            f'<div style="color:#5a7a9a;font-size:0.75rem">chunks</div>',
            unsafe_allow_html=True,
        )
    with col2:
        st.markdown(
            f'<div class="doc-count">{len(source_names)}</div>'
            f'<div style="color:#5a7a9a;font-size:0.75rem">sources</div>',
            unsafe_allow_html=True,
        )

    st.markdown("**Sources loaded:**")
    for src in source_names:
        short = src if len(src) <= 35 else "..." + src[-32:]
        st.markdown(f'<span class="source-tag">{short}</span>', unsafe_allow_html=True)


# ── Chat Messages ─────────────────────────────────────────────────────────────


def render_user_message(content: str):
    """Render a user chat bubble."""
    st.markdown('<div class="chat-user-label">You</div>', unsafe_allow_html=True)
    st.markdown(
        f'<div class="chat-user-bubble">{content}</div>', unsafe_allow_html=True
    )


def render_assistant_message(content: str, queries: list, sources: list):
    """Render assistant answer with formatted markdown + collapsible details."""
    st.markdown(
        '<div class="chat-assistant-label">🔬 Research Assistant</div>',
        unsafe_allow_html=True,
    )

    # Render full markdown — bullet points, bold, headers all work here
    st.markdown(content)

    # Collapsible RAG details
    if queries:
        with st.expander("🔍 View RAG Fusion Queries + Sources"):
            st.markdown("**Queries generated by RAG Fusion:**")
            for q in queries:
                st.markdown(
                    f'<span class="query-tag">↳ {q}</span>', unsafe_allow_html=True
                )

            if sources:
                st.markdown("<br>**Retrieved from:**", unsafe_allow_html=True)
                for src in sources:
                    short = src if len(src) <= 60 else "..." + src[-57:]
                    st.markdown(
                        f'<span class="source-tag">📄 {short}</span>',
                        unsafe_allow_html=True,
                    )

    st.divider()


def render_chat_history(chat_history: list):
    """Render the full chat history."""
    for msg in chat_history:
        if msg["role"] == "user":
            render_user_message(msg["content"])
        else:
            render_assistant_message(
                content=msg["content"],
                queries=msg.get("queries", []),
                sources=msg.get("sources", []),
            )
